name: CaptchaVerification
description: Now You can Verify Bot or Human to Join this server
author: XanderID
version: 1.0.0
api: 4.0.0
main: XanderID\CaptchaVerification\CaptchaVerification

depend:
 - ImageOnMap